### PR TITLE
Migrate from webpack to esbuild

### PR DESCRIPTION
**Pull request by jedahan**
This makes saxi buildable on a raspberry pi zero (webpack OOMs even with 1.5Gb of memory).

This also enables live-reload during development.

This should also speed things up, but i haven't benchmarked it

### CODE REVIEW

**Comment by alexrudd2** [comment]
```
npm run dev
<snip>
npm ERR! Missing script: "serve"
npm ERR!
```

The line in question is a script in `package.json`.  `{ "dev": "npm run serve & BUILD_MODE=development npm run build:ui",`.

Is this supposed to be `npm run build:server` or something?

**Review by alexrudd2 — COMMENTED** [review]
The Typescript downgrade shouldn't be necessary if you upgrade `typescript-eslint`, since it recently added support for 5.2

https://github.com/typescript-eslint/typescript-eslint/pull/7535

**Comment by jedahan** [comment]
ahh yeah, I will add the missing serve script and upgrade typescript-eslint

**Comment by alexrudd2** [comment]
As I commented on the other PR, my intention is to merge all these changes into `nornagon/saxi` in manageable chunks rather than maintain a fork.

That said, works for me so thanks :)

**Comment by alexrudd2** [comment]
https://github.com/alexrudd2/saxi/pull/98 should be included here

**Pull request merged**
