### PR TITLE
Migrate to preact

### PR DESCRIPTION
**Pull request by jedahan**
This reduces the minified bundle size by 50%

Happy to throw away if there are worries, but if its good enough for Etsy it's probably good enough for us?

### CODE REVIEW

**Comment by jedahan** [comment]
Screenshot 2023-10-04 at 6 07 58 PM
Screenshot 2023-10-04 at 6 15 12 PM

**Comment by alexrudd2** [comment]
I don't care one way or the other, so I guess default to keeping as-is.

How much does bundle size affect your performance on a Zero W?

**Comment by jedahan** [comment]
Its mostly a "smaller bundle means less code means less bugs" kinda thing. I don't have any performance metrics I've recorded.

**Comment by alexrudd2** [comment]
I've gone and resuscitated [lineboi3000](https://github.com/alexrudd2/lineboi3000) (since I saw you playing with it).

If it's all the same to you, I'd rather keep both projects on the same framework.  Performance is still good for you, right?

**Comment by jedahan** [comment]
Both projects on the same framework sounds good to me.

**Pull request closed without merging**
