### PR TITLE
Describe rpi 0/1 install process

### PR DESCRIPTION
**Pull request by jedahan**
Had to use the unofficial build

### CODE REVIEW

**Comment by osresearch** [comment]
Trying this on my Pi Zero W (512 MB) results in running out of memory:
```
pi@plotter:~/saxi $ npm install 
> saxi@0.15.0 prepare
> rimraf dist && npm run build

> saxi@0.15.0 prebuild
> npm run lint

> saxi@0.15.0 lint
> eslint --cache --ext .ts,.tsx src

> saxi@0.15.0 build
> tsc && webpack --mode=production

<--- Last few GCs --->

[24524:0x5f5eaf0]   253322 ms: Scavenge 123.1 (128.7) -> 123.0 (128.7) MB, 14.28 / 0.00 ms  (average mu = 0.554, current mu = 0.129) allocation failure; 
[24524:0x5f5eaf0]   253382 ms: Scavenge 123.1 (128.7) -> 123.0 (129.2) MB, 22.51 / 0.00 ms  (average mu = 0.554, current mu = 0.129) allocation failure; 
[24524:0x5f5eaf0]   257224 ms: Mark-Compact 123.4 (129.2) -> 123.0 (129.7) MB, 3464.13 / 0.00 ms  (average mu = 0.404, current mu = 0.145) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
Aborted
npm ERR! code 134
npm ERR! path /home/pi/saxi
npm ERR! command failed
npm ERR! command sh -c rimraf dist && npm run build

npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2023-11-14T11_21_59_716Z-debug-0.log
```

version info:
```
pi@plotter:~/saxi $ which npm ; npm --version
/home/pi/saxi/node-v20.5.1-linux-armv6l/bin/npm
9.8.0
pi@plotter:~/saxi $ git rev-parse HEAD ; git status
53b14a09a4134dd0f19dbc9aa820c63e10e22537
On branch main
Your branch is up to date with 'origin/main'.
```

**Comment by jedahan** [comment]
Please update the repository with a `git pull` and try again - that build log shows you are using webpack, but we switched to esbuild maybe a dozen commits after that one, so that it can build on a pi zero.

**Comment by alexrudd2** [comment]
> Please update the repository with a `git pull` and try again - that build log shows you are using webpack, but we switched to esbuild maybe a dozen commits after that one, so that it can build on a pi zero.

Note that you'll have to have `git` pointed to this fork and not `nornagon/saxi`

**Comment by osresearch** [comment]
aaargh I thought I was on the right branch,... switching to a2ac49f690c1aec5a7c265190df47437abbdd1fa didn't fix the memory exhaustion, so I added a 1GB swap file, and that didn't work either which surprised me.  it looks like `tsc` doesn't fill all available RAM by default, so I added an explicit heap size (1 GB == 1024KB) and it was able to complete:

```
diff --git a/package.json b/package.json
index 7400185..cb6f1c6 100644
--- a/package.json
+++ b/package.json
@@ -22,7 +22,7 @@
     "prebuild": "npm run lint",
     "lint": "eslint --cache --ext .ts,.tsx src",
     "build": "npm run build:server && npm run build:ui",
-    "build:server": "tsc",
+    "build:server": "NODE_OPTIONS='--max-old-space-size=1024' tsc",
     "build:ui": "node --experimental-modules build.mjs",
     "prepare": "rimraf dist && npm run build",
     "prestart": "npm run build",
```

**Pull request merged**
